// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5uyxSH5_0ki5ng3zsy4Nh2H7SdJ3TJH4',
    appId: '1:1039495274176:web:acad853667e0913e5ad725',
    messagingSenderId: '1039495274176',
    projectId: 'coffee-app-a2521',
    authDomain: 'coffee-app-a2521.firebaseapp.com',
    storageBucket: 'coffee-app-a2521.appspot.com',
    measurementId: 'G-XBL0TLRXT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyk8A_K76wYOhZhXU7JAUl8OHs6NaMViA',
    appId: '1:1039495274176:android:7de31e321232ecd65ad725',
    messagingSenderId: '1039495274176',
    projectId: 'coffee-app-a2521',
    storageBucket: 'coffee-app-a2521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-oP_fuNjR5IWBKnjgkx9-Tm5ad1AWiiI',
    appId: '1:1039495274176:ios:c40f970391296d755ad725',
    messagingSenderId: '1039495274176',
    projectId: 'coffee-app-a2521',
    storageBucket: 'coffee-app-a2521.appspot.com',
    iosClientId: '1039495274176-tqm5q9t3fs8ge886n6tcj0jj2efr49n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-oP_fuNjR5IWBKnjgkx9-Tm5ad1AWiiI',
    appId: '1:1039495274176:ios:c40f970391296d755ad725',
    messagingSenderId: '1039495274176',
    projectId: 'coffee-app-a2521',
    storageBucket: 'coffee-app-a2521.appspot.com',
    iosClientId: '1039495274176-tqm5q9t3fs8ge886n6tcj0jj2efr49n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSocial',
  );
}
